name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Starting build
        run: ./scripts/build.sh
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running tests
        run: ./scripts/test.sh
        
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Building a deb package
        run: ./scripts/package.sh
        